	version: "3"

services:

  mosquitto:
    image: "eclipse-mosquitto:latest"
    container_name: mosquitto
    restart: "always"
    ports:
      - "1883:1883"
    volumes:
      - "./mosquitto:/mosquitto/config/:ro"
      - "mosquitto-storage:/mosquitto/data"
      - "mosquitto-storage:/mosquitto/log"
  
  bridge:
    restart: always
    build: ./bridge
    depends_on:
    - influxdb
    - mosquitto
  
  influxdb:
    image: influxdb
    container_name: influxdb
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086

  grafana:
    image: grafana/grafana-oss:8.4.3
    container_name: grafana
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT}:3000





volumes:
  grafana-storage:
  influxdb-storage:
  mosquitto-storage:
  jupyterlab-data:
